# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'vector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvector.proto\"\x1e\n\x0e\x63onvertRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"!\n\x0f\x63onvertResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32@\n\nTextVector\x12\x32\n\rconvertVector\x12\x0f.convertRequest\x1a\x10.convertResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERTREQUEST']._serialized_start=16
  _globals['_CONVERTREQUEST']._serialized_end=46
  _globals['_CONVERTRESPONSE']._serialized_start=48
  _globals['_CONVERTRESPONSE']._serialized_end=81
  _globals['_TEXTVECTOR']._serialized_start=83
  _globals['_TEXTVECTOR']._serialized_end=147
# @@protoc_insertion_point(module_scope)
